#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

NAME="spectr-utmc-bridge"
PROG="/usr/sbin/spectr-utmc-bridge"
CFG="/etc/spectr-utmc/config.json"

start_service() {
	[ -x "$PROG" ] || return 1
	[ -f "$CFG" ] || return 1

	procd_open_instance
	procd_set_param command "$PROG" "$CFG"
	procd_set_param respawn 3600 5 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	stop
	start
}

